# Generated by Django 5.2.3 on 2025-06-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='group',
        ),
    ]
