# Generated by Django 5.2.3 on 2025-06-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_pet'),
        ('pets', '0002_remove_pet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='groups.group'),
            preserve_default=False,
        ),
    ]
