# Generated by Django 5.2.3 on 2025-06-12 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('pets', '0002_remove_pet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='pets.pet'),
            preserve_default=False,
        ),
    ]
