# Generated by Django 5.2.3 on 2025-06-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pet',
        ),
    ]
